pull_request_rules:
  - name: Automatic rebase for PRs marked as "keep-up-to-date"
    conditions:
      - label=keep-up-to-date
      - -draft
    actions:
      update:

  - name: Automatic merge when CI passes
    conditions:
      - check-success=nix-flake-check
    actions:
      merge:
        method: rebase
      delete_head_branch:

  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
