queue_rules:
  - name: default
    queue_conditions:
      - check-success=All Garnix checks
      - -title ~= (?i)wip
      - -merged
      - -closed
      - -draft
      - -author~=\[bot\]$
    merge_conditions: []
    merge_method: rebase
    update_method: rebase

pull_request_rules:
  - name: Automatic rebase for PRs marked as "keep-up-to-date"
    conditions:
      - label=keep-up-to-date
      - -draft
      - -merged
      - -closed
    actions:
      update:

  - name: Automatic merge when CI passes
    conditions: []
    actions:
      queue:
      delete_head_branch:

  - name: Toggle conflict label based on mergeability
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"

  - name: Label WIP PRs
    conditions:
      - title ~= (?i)wip
    actions:
      label:
        add:
          - WIP
