pull_request_rules:
  - name: Automatic rebase for PRs marked as "keep-up-to-date"
    conditions:
      - label=keep-up-to-date
      - label!=CI:fail
      - -draft
    actions:
      update:

  - name: Automatic merge when CI passes
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=All Garnix checks
      - label!=conflict
    actions:
      merge:
        method: rebase
      delete_head_branch:

  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict

  - name: Add CI:fail label when CI fails
    conditions:
      - check-failure=All Garnix checks
    actions:
      label:
        add:
          - CI:fail

  - name: Remove CI:fail label when CI passes
    conditions:
      - check-success=All Garnix checks
    actions:
      label:
        remove:
          - CI:fail

  - name: Add "WIP" label when the title contains "WIP"
    conditions:
      - title~=WIP
    actions:
      label:
        add:
          - WIP

  - name: Close stale pull requests
    conditions:
      - updated-at<=30 days ago
      - label!=keep-open
      - -merged
      - -draft
    actions:
      comment:
        message: "This PR has been inactive for 30 days and will be closed soon. 💤"
      close:
