# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  app2unit = {
    pname = "app2unit";
    version = "83e2656fb8d39ad71e2f8a5ba113a9cedc90841f";
    src = fetchgit {
      url = "https://github.com/Vladimir-csp/app2unit";
      rev = "83e2656fb8d39ad71e2f8a5ba113a9cedc90841f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DZ0W7SygOUmjIO0+K8hS9K1U+gSp1gA6Q15eXr6rOmo=";
    };
    date = "2025-11-28";
  };
  catppuccin-fcitx5 = {
    pname = "catppuccin-fcitx5";
    version = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
    src = fetchgit {
      url = "https://github.com/catppuccin/fcitx5";
      rev = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ss0kW+ulvMhxeZKBrjQ7E5Cya+02eJrGsE4OLEkqKks=";
    };
    date = "2025-05-16";
  };
  firefox-csshacks = {
    pname = "firefox-csshacks";
    version = "2f30a2283ba09c5934f474110a8be462482eb272";
    src = fetchgit {
      url = "https://github.com/MrOtherGuy/firefox-csshacks";
      rev = "2f30a2283ba09c5934f474110a8be462482eb272";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aAwiI6+QWPQuEGdz0Ey57RFMakM7XuBYiUJuANxECgM=";
    };
    date = "2025-11-12";
  };
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "f7ffd917ac0d253dbd6a3bf3da06888f57c69f92";
    src = fetchgit {
      url = "https://github.com/rafaelmardojai/firefox-gnome-theme";
      rev = "f7ffd917ac0d253dbd6a3bf3da06888f57c69f92";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1XPewtGMi+9wN9Ispoluxunw/RwozuTRVuuQOmxzt+A=";
    };
    date = "2025-12-04";
  };
  firefox-ui-fix = {
    pname = "firefox-ui-fix";
    version = "9942096af6ebf7e2653f5178851848e286bd679f";
    src = fetchgit {
      url = "https://github.com/black7375/Firefox-UI-Fix";
      rev = "9942096af6ebf7e2653f5178851848e286bd679f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+uYMq5ZGpW99mE6fl0Uy9+ardhyPbDirw4JZLFtutZo=";
    };
    date = "2025-11-30";
  };
  fuzzmoji = {
    pname = "fuzzmoji";
    version = "af4baa86611f2dfbe66c845f1b7edb582efc6cb5";
    src = fetchgit {
      url = "https://codeberg.org/codingotaku/fuzzmoji";
      rev = "af4baa86611f2dfbe66c845f1b7edb582efc6cb5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M3Sv7OLpUO84A1yS/TobxHVrBbwgedX8wNq58ZuJhKM=";
    };
    date = "2025-07-06";
  };
  npins = {
    pname = "npins";
    version = "84a362d77fb3c487ad759c80547facb028f4d96f";
    src = fetchgit {
      url = "https://github.com/andir/npins";
      rev = "84a362d77fb3c487ad759c80547facb028f4d96f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-EWA14ovB/5UFiK9fmEYtofIMbGnVeJ/4yK0aJEJXtsI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./npins-84a362d77fb3c487ad759c80547facb028f4d96f/Cargo.lock;
      outputHashes = {
        "nix-compat-0.1.0" = "sha256-ehkc7ug0HkTHKxx9tQi/9vkOtQry9HdiX9UxBUvjYRY=";
      };
    };
    date = "2025-11-26";
  };
  runapp = {
    pname = "runapp";
    version = "10fb4b344d06c815c1cd4c1b8bdc4f797b04230f";
    src = fetchgit {
      url = "https://github.com/c4rlo/runapp";
      rev = "10fb4b344d06c815c1cd4c1b8bdc4f797b04230f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KH/dK2aYviV5a2L/C4wb3fAHbdGChrpHP53RlLejyoA=";
    };
    date = "2025-11-26";
  };
  san-francisco-fonts = {
    pname = "san-francisco-fonts";
    version = "5a8fc7d569fa2b4fb5fe9a63ad66e5cf9ae00eae";
    src = fetchgit {
      url = "https://github.com/oyezcubed/Apple-Fonts-San-Francisco-New-York";
      rev = "5a8fc7d569fa2b4fb5fe9a63ad66e5cf9ae00eae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NBvWqHMaieaCZffqNitnhn979Sl2bAkIwC5sWW24z7g=";
    };
    date = "2020-08-27";
  };
  san-francisco-pro = {
    pname = "san-francisco-pro";
    version = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
    src = fetchgit {
      url = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts";
      rev = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mAXExj8n8gFHq19HfGy4UOJYKVGPYgarGd/04kUIqX4=";
    };
    date = "2021-06-22";
  };
  wezterm = {
    pname = "wezterm";
    version = "d3b0fdad453e8b5f12b583c5d6849b33d975c19c";
    src = fetchgit {
      url = "https://github.com/wez/wezterm";
      rev = "d3b0fdad453e8b5f12b583c5d6849b33d975c19c";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UmhJ0Z9A9AnbHG8/fADbXIjNm+Mpt2+h6xznJs39M8E=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wezterm-d3b0fdad453e8b5f12b583c5d6849b33d975c19c/Cargo.lock;
      outputHashes = {
        "xcb-imdkit-0.3.0" = "sha256-rP4oKkZ0aC4/5Jm8t5Ru7n3qLHw74/58A0Gt+sygQgU=";
        "finl_unicode-1.3.0" = "sha256-38S6XH4hldbkb6NP+s7lXa/NR49PI0w3KYqd+jPHND0=";
      };
    };
    date = "2025-12-01";
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "60e7f1b4c26cde034049d0da89d415218f479314";
    src = fetchgit {
      url = "https://github.com/vinceliuice/WhiteSur-gtk-theme";
      rev = "60e7f1b4c26cde034049d0da89d415218f479314";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XXGWMdBgGC2uB2TnAYxcYVCySZJc28EIyLAE4ZNwVtM=";
    };
    date = "2025-11-09";
  };
}
