# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  app2unit = {
    pname = "app2unit";
    version = "83e2656fb8d39ad71e2f8a5ba113a9cedc90841f";
    src = fetchgit {
      url = "https://github.com/Vladimir-csp/app2unit";
      rev = "83e2656fb8d39ad71e2f8a5ba113a9cedc90841f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DZ0W7SygOUmjIO0+K8hS9K1U+gSp1gA6Q15eXr6rOmo=";
    };
    date = "2025-11-28";
  };
  catppuccin-fcitx5 = {
    pname = "catppuccin-fcitx5";
    version = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
    src = fetchgit {
      url = "https://github.com/catppuccin/fcitx5";
      rev = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ss0kW+ulvMhxeZKBrjQ7E5Cya+02eJrGsE4OLEkqKks=";
    };
    date = "2025-05-16";
  };
  firefox-csshacks = {
    pname = "firefox-csshacks";
    version = "1a3b86bff806571f5f235a779263a2c9c7b7419b";
    src = fetchgit {
      url = "https://github.com/MrOtherGuy/firefox-csshacks";
      rev = "1a3b86bff806571f5f235a779263a2c9c7b7419b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Oq6n8Ag5x1IahEg+1KpJgRdd+YyaJHuxLt7KSGEzAZM=";
    };
    date = "2026-01-04";
  };
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "f7ffd917ac0d253dbd6a3bf3da06888f57c69f92";
    src = fetchgit {
      url = "https://github.com/rafaelmardojai/firefox-gnome-theme";
      rev = "f7ffd917ac0d253dbd6a3bf3da06888f57c69f92";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1XPewtGMi+9wN9Ispoluxunw/RwozuTRVuuQOmxzt+A=";
    };
    date = "2025-12-04";
  };
  firefox-ui-fix = {
    pname = "firefox-ui-fix";
    version = "556924cc43f228991adb8f8e3170230774b2849c";
    src = fetchgit {
      url = "https://github.com/black7375/Firefox-UI-Fix";
      rev = "556924cc43f228991adb8f8e3170230774b2849c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cWk72ZgZSBDVD1uJA5gC2kbiYtJcUY059oy+VhC8UWg=";
    };
    date = "2026-01-01";
  };
  fuzzmoji = {
    pname = "fuzzmoji";
    version = "af4baa86611f2dfbe66c845f1b7edb582efc6cb5";
    src = fetchgit {
      url = "https://codeberg.org/codingotaku/fuzzmoji";
      rev = "af4baa86611f2dfbe66c845f1b7edb582efc6cb5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M3Sv7OLpUO84A1yS/TobxHVrBbwgedX8wNq58ZuJhKM=";
    };
    date = "2025-07-06";
  };
  npins = {
    pname = "npins";
    version = "3329242072a414c5a25aa8d95a56d8afa013a3fa";
    src = fetchgit {
      url = "https://github.com/andir/npins";
      rev = "3329242072a414c5a25aa8d95a56d8afa013a3fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-bnyv87sV5Fj6RTdg/3j24vea6ctSSjDrdshR90qt4O0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./npins-3329242072a414c5a25aa8d95a56d8afa013a3fa/Cargo.lock;
      outputHashes = {
        "nix-compat-0.1.0" = "sha256-w8N09ZUm0V+6LdjGyL6g0mb3COoNWONfmr/M3S9C+do=";
      };
    };
    date = "2026-01-06";
  };
  runapp = {
    pname = "runapp";
    version = "10fb4b344d06c815c1cd4c1b8bdc4f797b04230f";
    src = fetchgit {
      url = "https://github.com/c4rlo/runapp";
      rev = "10fb4b344d06c815c1cd4c1b8bdc4f797b04230f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KH/dK2aYviV5a2L/C4wb3fAHbdGChrpHP53RlLejyoA=";
    };
    date = "2025-11-26";
  };
  san-francisco-fonts = {
    pname = "san-francisco-fonts";
    version = "5a8fc7d569fa2b4fb5fe9a63ad66e5cf9ae00eae";
    src = fetchgit {
      url = "https://github.com/oyezcubed/Apple-Fonts-San-Francisco-New-York";
      rev = "5a8fc7d569fa2b4fb5fe9a63ad66e5cf9ae00eae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NBvWqHMaieaCZffqNitnhn979Sl2bAkIwC5sWW24z7g=";
    };
    date = "2020-08-27";
  };
  san-francisco-pro = {
    pname = "san-francisco-pro";
    version = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
    src = fetchgit {
      url = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts";
      rev = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mAXExj8n8gFHq19HfGy4UOJYKVGPYgarGd/04kUIqX4=";
    };
    date = "2021-06-22";
  };
  wezterm = {
    pname = "wezterm";
    version = "4bcb2b32ce61f6935867a85700deac5f56caf583";
    src = fetchgit {
      url = "https://github.com/wez/wezterm";
      rev = "4bcb2b32ce61f6935867a85700deac5f56caf583";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-yDxmO7VGQNsV6cX4dsj1vSxuHL6CU25zdy8T8E0/90I=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wezterm-4bcb2b32ce61f6935867a85700deac5f56caf583/Cargo.lock;
      outputHashes = {
        "xcb-imdkit-0.3.0" = "sha256-rP4oKkZ0aC4/5Jm8t5Ru7n3qLHw74/58A0Gt+sygQgU=";
        "finl_unicode-1.3.0" = "sha256-38S6XH4hldbkb6NP+s7lXa/NR49PI0w3KYqd+jPHND0=";
      };
    };
    date = "2026-01-07";
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "7ce45b4593cc5dc0073536e48761235c4acfe477";
    src = fetchgit {
      url = "https://github.com/vinceliuice/WhiteSur-gtk-theme";
      rev = "7ce45b4593cc5dc0073536e48761235c4acfe477";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+P6spRS71hWWkQSG7SgYgZm9KQNH3vQbn27e8Hjim4Y=";
    };
    date = "2026-01-05";
  };
}
