# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  app2unit = {
    pname = "app2unit";
    version = "fc2f7250fa1419204211c531612395427c660d01";
    src = fetchgit {
      url = "https://github.com/Vladimir-csp/app2unit";
      rev = "fc2f7250fa1419204211c531612395427c660d01";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-upYW+aTJ6LCHrI0+IOYnA98uDLKPxu/wCi7uUWe/Geg=";
    };
    date = "2026-04-23";
  };
  catppuccin-fcitx5 = {
    pname = "catppuccin-fcitx5";
    version = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
    src = fetchgit {
      url = "https://github.com/catppuccin/fcitx5";
      rev = "393845cf3ed0e0000bfe57fe1b9ad75748e2547f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ss0kW+ulvMhxeZKBrjQ7E5Cya+02eJrGsE4OLEkqKks=";
    };
    date = "2025-05-16";
  };
  firefox-csshacks = {
    pname = "firefox-csshacks";
    version = "4f47bb1866f867bbdb3603f21762d5355a61e415";
    src = fetchgit {
      url = "https://github.com/MrOtherGuy/firefox-csshacks";
      rev = "4f47bb1866f867bbdb3603f21762d5355a61e415";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GQxxJGWNfOP/wPLPhukyZKbPV59DlPjRo16IG0miXio=";
    };
    date = "2026-05-24";
  };
  firefox-gnome-theme = {
    pname = "firefox-gnome-theme";
    version = "942159e73e40bf785816f7f1f5feed9ef3d7c8f9";
    src = fetchgit {
      url = "https://github.com/rafaelmardojai/firefox-gnome-theme";
      rev = "942159e73e40bf785816f7f1f5feed9ef3d7c8f9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UdfMivNMwCCqQsYDg5pSz8X2IOaOrIZLIIy+Bg3CO2o=";
    };
    date = "2026-05-24";
  };
  firefox-ui-fix = {
    pname = "firefox-ui-fix";
    version = "556924cc43f228991adb8f8e3170230774b2849c";
    src = fetchgit {
      url = "https://github.com/black7375/Firefox-UI-Fix";
      rev = "556924cc43f228991adb8f8e3170230774b2849c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cWk72ZgZSBDVD1uJA5gC2kbiYtJcUY059oy+VhC8UWg=";
    };
    date = "2026-01-01";
  };
  fuzzmoji = {
    pname = "fuzzmoji";
    version = "bce00ef8f9fc1078365120ab8916cfce3fd897fa";
    src = fetchgit {
      url = "https://codeberg.org/codingotaku/fuzzmoji";
      rev = "bce00ef8f9fc1078365120ab8916cfce3fd897fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xeAoL15Uc2bkbhp95dUT3/mwtR1eDtJCAfjjJCjlfXE=";
    };
    date = "2026-03-02";
  };
  runapp = {
    pname = "runapp";
    version = "1ba272ec2e7fbb7c7fd353283a2430dd5f704df2";
    src = fetchgit {
      url = "https://github.com/c4rlo/runapp";
      rev = "1ba272ec2e7fbb7c7fd353283a2430dd5f704df2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-V9MYExbLIKpAB9sXDaBkiNgCiHJb+nDK7rvKHV/zsDE=";
    };
    date = "2026-05-10";
  };
  san-francisco-fonts = {
    pname = "san-francisco-fonts";
    version = "5a8fc7d569fa2b4fb5fe9a63ad66e5cf9ae00eae";
    src = fetchgit {
      url = "https://github.com/oyezcubed/Apple-Fonts-San-Francisco-New-York";
      rev = "5a8fc7d569fa2b4fb5fe9a63ad66e5cf9ae00eae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NBvWqHMaieaCZffqNitnhn979Sl2bAkIwC5sWW24z7g=";
    };
    date = "2020-08-27";
  };
  san-francisco-pro = {
    pname = "san-francisco-pro";
    version = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
    src = fetchgit {
      url = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts";
      rev = "8bfea09aa6f1139479f80358b2e1e5c6dc991a58";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mAXExj8n8gFHq19HfGy4UOJYKVGPYgarGd/04kUIqX4=";
    };
    date = "2021-06-22";
  };
  whitesur-gtk-theme = {
    pname = "whitesur-gtk-theme";
    version = "a83f467e4c16b1ed1c960f3d89e2472d9639477c";
    src = fetchgit {
      url = "https://github.com/vinceliuice/WhiteSur-gtk-theme";
      rev = "a83f467e4c16b1ed1c960f3d89e2472d9639477c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-zbYLek+OYizrtvV7zcaYENqZAuunNcg1gfFJ+3atuSc=";
    };
    date = "2026-05-25";
  };
}
