name: "Nix Flake Check"
on:
  pull_request:
  push:

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.3
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        diagnostic-endpoint: ''
        source-url: 'https://install.lix.systems/lix/lix-installer-x86_64-linux'
        extra-conf: |
          http2 = false
    - run: nix flake check --show-trace
