name: Update Flakes

on:
  workflow_dispatch:
  schedule:
    # Sunday 17:00 UTC -> Monday 03:00 JST
    - cron: "0 18 * * 0"
    # Wednesday 17:00 UTC -> Thursday 03:00 JST
    - cron: "0 18 * * 3"

jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@latest

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          # These determine what shows up in "git log"
          git-author-name: "Ludovico Piero"
          git-author-email: "lewdovico@gnuweeb.org"
          git-committer-name: "Ludovico Piero"
          git-committer-email: "lewdovico@gnuweeb.org"
          commit-msg: "chore: Update flake.lock"
          pr-title: "Update flake.lock"
          pr-labels: |
            automated
            keep-up-to-date
