name: "Update Packages"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"

jobs:
  nvfetcher-update:
    if: github.repository == 'ludovicopiero/dotfiles' # Don't do this in forks
    runs-on: ubuntu-latest
    outputs:
      id: pr
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.PR_TOKEN }}"

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Git config
        run: |
          git config --global user.email "maximiliansforza@proton.me"
          git config --global user.name "Maximilian Sforza"

      - name: Run nvfetcher
        run: |
          pushd packages
          rm -r _sources/wezterm-*
          nix run github:berberman/nvfetcher -- --commit-changes
          popd

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ secrets.PR_TOKEN }}"
          title: "Package Update"
          body: "BOOMP BOOMP"
          labels: automated,uwu, keep-up-to-date
          branch: "nvfetcher-update"
          delete-branch: true

  nix-update:
    if: github.repository == 'ludovicopiero/dotfiles' # Don't do this in forks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages:
          - iosevka-q
          - sarasa-gothic
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.PR_TOKEN }}"

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Git config
        run: |
          git config --global user.email "maximiliansforza@proton.me"
          git config --global user.name "Maximilian Sforza"

      - name: Run nix-update
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8

          nix run nixpkgs#nix-update -- --flake ${{ matrix.packages }} --commit

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ secrets.PR_TOKEN }}"
          title: "Package Update for ${{ matrix.packages }}"
          body: "Automated package update for ${{ matrix.packages }}"
          labels: automated,uwu, keep-up-to-date
          branch: "nix-update-${{ matrix.packages }}-${{ github.run_id }}"
          delete-branch: true
