name: "Update Packages"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * 0"

jobs:
  update-packages:
    if: github.repository == 'ludovicopiero/dotfiles'  # Don't run in forks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.PR_TOKEN }}"

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Git config
        run: |
          git config --global user.email "maximiliansforza@proton.me"
          git config --global user.name "Maximilian Sforza"

      - name: Run nvfetcher updates
        run: |
          pushd packages
          nix run github:berberman/nvfetcher -- --commit-changes
          popd

      - name: Run nix-update for all flakes
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          for pkg in iosevka-q sarasa-gothic tidal-hifi; do
            nix run nixpkgs#nix-update -- --flake "$pkg" --commit
          done

      - name: Create or update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ secrets.PR_TOKEN }}"
          title: "Automated package updates"
          body: |
            This PR combines:
            - nvfetcher source updates
            - nix-update for iosevka-q, sarasa-gothic, tidal-hifi
          labels: automated, uwu, keep-up-to-date
          branch: "package-update"
          delete-branch: true
